### ISSUE TITLE
Wagner2018_Chordin_Cas9_Mutagenesis is not reproducible

### ISSUE THREAD

**Issue by VPetukhov** [KrishnaswamyLab/MELD#40]
Hi, thank you for the interesting package! I'm trying to reproduce the [Wagner2018_Chordin_Cas9_Mutagenesis](https://github.com/KrishnaswamyLab/MELD/blob/master/notebooks/Wagner2018_Chordin_Cas9_Mutagenesis.ipynb) notebook, but it doesn't work in multiple places: some variables are used before they're defined, some names does not match (e.g. somewhere `sample_label` is called `sample_labels`, which crashes the code), and some variables are just note defined (particularly, "RES" column in the `metadata`). Also, the table of content does not match to the current headings. Could you please fix the thing? :)

**Comment by dburkhardt** [comment]
Hi, sorry about this. It looks like I just forgot to merge the updated notebook into the master branch. I should be able to finish the PR shortly. Thanks for bringing this to my attention!

**Comment by VPetukhov** [comment]
Thanks!
