### ISSUE TITLE
can't find get_cmap function

### ISSUE THREAD

**Issue by wupeng2** [KrishnaswamyLab/MELD#42]
hello,
when I run the Jupyter notebook ,I got the question below:
AttributeError: module 'meld' has no attribute 'get_cmap'
whether use meld  3.0.1 or  meld  3.0.0,i've got the same error.
 Look forward to your reply.
thanks

**Comment by dburkhardt** [comment]
Hi @wupeng2, it looks like you've probably installed the wrong package, the current version of MELD is 0.3.0 (https://pypi.org/project/meld/) Can you try installing from PyPI?

**Comment by dburkhardt** [comment]
Actually, my bad. It looks like that import didn't get uploaded properly. For now, you can get that colormap here: `meld.utils.get_meld_cmap()`

**Comment by wupeng2** [comment]
I've sloved this problem by using meld.utils.get_meld_cmap instead of get_cmap,and run the jupyter notebook successfully
thanks
