### ISSUE TITLE
Get aData object to process MELD graph parameters

### ISSUE THREAD

**Issue by Baboon61** [KrishnaswamyLab/MELD#51]
Super interesting work and congratulations for the Nature Biotech !

I am trying to run your in depth tutorial on my own dataset and as recommended in your notebook, one should reprocess the graph parameters for the MELD algorithm because the best beta and knn parameters may vary according to dataset size and structure.

Running the `meld.Benchmarker()` I came across this function `benchmarker.fit_graph(adata.X, knn=knn)` where `aData` seems to be an `agraph object` to pass as input to the `fit_graph` function.

I did not find any information about how to get this object in your notebooks or in the manuscript. Can you help me get this object ? Thanks !

**Comment by dburkhardt** [comment]
Oh that's an AnnData object: https://anndata.readthedocs.io

**Comment by Baboon61** [comment]
`benchmarker.fit_graph(data_libnorm, knn=knn)` should do it then ,thanks !
