### ISSUE TITLE
Using graph from Scanpy

### ISSUE THREAD

**Issue by Hrovatin** [KrishnaswamyLab/MELD#52]
Is there a way to use MELD with a graph from Scanpy? I have some large datasets and I would like to avoid recomputing graphs, since my adata already contains a graph and I can easily save it together with my adata if I just use Scanpy. Not sure about how your graphtools graph works.

**Comment by Hrovatin** [comment]
Also, transform says 
```
 sample_indicators : ndarray [n, p]
            1- or 2-dimensional sample indicator array to filter.
```
But I get an error if I inpput already one-hot encoded labels as it expects categorical column it seems.
Could you enable passing of one hot encoding as I would like some cells to belong to no category (e.g. I do not want to compute densities for all categories).

**Comment by dburkhardt** [comment]
Hi @Hrovatin! Thanks for your interest in MELD. You can use the connecitivies matrix from `scanpy.pp.neighbors` to build a graphtools Graph and pass that to MELD like this:

```
G =  gt.Graph(adata.obsp["connectivities"], precomputed="adjacency")
meld_op.fit(G)
# Run on a 1-dimensional indicator vector
sample_densities = meld_op.transform(np.random.binomial(1, 0.5, size=G.N))
```

Then you could just take `sample_densities[1]` to get the density for the positive case. You can't calculate a likelihood here because you're not wanting the "not-1" case to be a category. Does that make sense? You'll need to use the densities for the `1` category as densities directly.

**Comment by Hrovatin** [comment]
Hi, Thank you for reply. I now get
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-cd043b11f202> in <module>
      1 # apply filter
----> 2 densities = meld.filter.filter(
      3     signal=meld_obj.sample_indicators,
      4     graph=meld_obj.graph,
      5     filter=meld_obj.filter,

~/miniconda3/envs/rpy2_3/lib/python3.8/site-packages/meld/filter.py in filter(signal, graph, filter, beta, offset, order, solver, chebyshev_order)
     37     """
     38 
---> 39     graph.estimate_lmax()
     40 
     41     # Generate MELD filter

AttributeError: 'TraditionalGraph' object has no attribute 'estimate_lmax'

**Comment by Hrovatin** [comment]
Thank you. 
However, I decided to do  normalization over conditions for which I computed MELD as this gives me results that better correspond to ground truth based on marker genes.

**Comment by dburkhardt** [comment]
Interesting, can you share that analysis/comparison? If you'd prefer to do it in a private channel you can find my email in my github profile.

**Comment by Hrovatin** [comment]
I have contacted you over email.

**Comment by Zethson** [comment]
@Hrovatin @dburkhardt would you two be willing to share the outcome of your discussion? I'd be interested in the conclusions.

Thanks!
