### ISSUE TITLE
UMAP instead of PHATE embedding

### ISSUE THREAD

**Issue by michallipinski** [KrishnaswamyLab/MELD#59]
Hello @dburkhardt and the Team!
I've just read your beautiful paper and I hope to apply MELD and VFC to my treatment scRNA-seq data. Just to start off, I am not a computational scientist but a humble biologist, so please bear with me.🥴

The one thing I've been a little stuck with is that PHATE is not really improving the visualization of my data (I tried many different knn and density values), as a matter of fact I can no longer see the clustering structure I see with UMAP or even t-SNE. So far it doesn't really seem to be a problem because the [MELD](https://github.com/KrishnaswamyLab/MELD/blob/master/meld/meld.py) and fit_transform don't use PHATE to compute. However if I want to follow your [in-depth tutorial](https://nbviewer.jupyter.org/github/KrishnaswamyLab/MELD/blob/master/notebooks/Wagner2018_Chordin_Cas9_Mutagenesis.ipynb) (which I do), the benchmarking tool uses an argument "data_phate". Can I use my UMAP embedding instead? Also, is PHATE embedding necessary in the downstream VFC analysis?

Thank you so much for your methods and help. Please correct me if what I misunderstood something.

**Comment by atong01** [comment]
Hi Michal, 

PHATE embedding is not necessary for either Meld or VFC. You can just substitute data_phate for any embedding and this should work fine.

One caveat, MELD and VFC, like many other methods, are built on top of a graph. By default this is the same graph as is used in the PHATE construction using the `graphtools` package. If your UMAP graph is substantially different then you may want to build Meld on top of this instead.
