### ISSUE TITLE
Treatment/Control Pairing 

### ISSUE THREAD

**Issue by paulstumpges** [KrishnaswamyLab/MELD#60]
Hi Daniel and team!
I just read your MELD paper (love it!) and hope to use MELD on my scRNA-Seq dataset. 
As you explain in the publication, for experiments comprising replicates, **matched** treatment and control conditions are normalized individually, and then the relative likelihood of each condition is averaged across replicates. This even gives you the possibility to get some understanding of how "stable" the relative likelihoods are across replicates, considering the standard deviation. 
In my dataset, I have an equal number of treatment and control samples. However, just based on the experimental design, there is not one single best way for me to match one treatment sample with one specific control sample. Many pairings of treatments and controls are possible and one combination is presumably not more "correct" than others. 
Do you have any advice for me on how to pair the samples into replicates of 1 treatment and 1 control? Is there any sample-specific parameter I could take into account? 
Thanks a lot!
Best,
Paul

**Comment by dburkhardt** [comment]
Hi @paulstumpges great question! I don't think there is a right answer to this question, but I have some ideas:

* You should still estimate the density of each label independently, this will give you some estimate of variability between replicates
* I would try averaging the control label density estimate and treatment label estimates and then do the normalization

Does that make sense? I think this is easier than trying to do all permutations of the signals against each other.

**Comment by paulstumpges** [comment]
Hi @dburkhardt!
Thanks for your answer! It definitely makes sense. I tried it out, and it seems to work well that way!
Best,
Paul
